# Bootcamp Numpy - Numpy Array

In [1]:
import numpy as np

In [2]:
# soal 1
matrix_x = np.array(
    [
        [10,20,30],
        [5,10,20],
        [2,4,6]
    ]
)
print(matrix_x)

[[10 20 30]
 [ 5 10 20]
 [ 2  4  6]]


In [3]:
# soal 2
matrix_y = np.array(
    [
        [
            [10, 20, 30],
            [5, 10, 20],
            [2, 4, 6]
        ],
        [
            [11, 20, 30],
            [5, 10, 20],
            [2, 4, 6]
        ],
        [
            [12, 20, 30],
            [5, 10, 20],
            [2, 4, 6]
        ],
    ]
)
print(matrix_y[2])

[[12 20 30]
 [ 5 10 20]
 [ 2  4  6]]


In [4]:
# soal 3
matrix_z = np.array(
    [
        [
            ['Macbook', 2, '25jt'],
            ['Macbook', 2, '25jt'],
            ['Macbook', 2, '25jt'],
        ],
        [
            ['Macbook', 2, '25jt'],
            ['Macbook', 2, '25jt'],
            ['Macbook', 2, '25jt'],
        ]
    ]
)
print(matrix_z)

[[['Macbook' '2' '25jt']
  ['Macbook' '2' '25jt']
  ['Macbook' '2' '25jt']]

 [['Macbook' '2' '25jt']
  ['Macbook' '2' '25jt']
  ['Macbook' '2' '25jt']]]


# Bootcamp Numpy - Numpy Array (Indexing and Slicing)

In [5]:
data = [
    ['Denis', 'Scratch', 8],
    ['Frank', 'Python', 18],
    ['Roger', 'Unity', 15],
]


# soal nomor 1
data = np.array(data)

# soal nomor 2
print(data[0])
print(data[1])
print(data[2])

# soal nomor 3
print(data[:,0])
print(data[:,1])
print(data[:,2])

# soal nomor 4
data[0,1] = 'Roblox'

['Denis' 'Scratch' '8']
['Frank' 'Python' '18']
['Roger' 'Unity' '15']
['Denis' 'Frank' 'Roger']
['Scratch' 'Python' 'Unity']
['8' '18' '15']


In [6]:
data_2 = [
    ['Java', 'Richie', 60, 'C'],
    ['Python', 'Niels', 80, 'A'],
    ['R', 'Brie', 75, 'B'],
]

#soal nomor 1
data_2 = np.array(data_2)

# soal nomor 2
print(data_2[0])
print(data_2[1])
print(data_2[2])

# soal nomor 3
print(data_2[:,0])
print(data_2[:,1])
print(data_2[:,2])
print(data_2[:,2])

# soal nomor 4
data_2[:,0] = "Data Analyst"
print(data_2)

['Java' 'Richie' '60' 'C']
['Python' 'Niels' '80' 'A']
['R' 'Brie' '75' 'B']
['Java' 'Python' 'R']
['Richie' 'Niels' 'Brie']
['60' '80' '75']
['60' '80' '75']
[['Data Analys' 'Richie' '60' 'C']
 ['Data Analys' 'Niels' '80' 'A']
 ['Data Analys' 'Brie' '75' 'B']]


In [7]:
data_2.shape

(3, 4)

# Bootcamp Pandas - Series - Creating, Indexing, and Selecting a Series
***
https://towardsdatascience.com/how-to-use-loc-and-iloc-for-selecting-data-in-pandas-bd09cb4c3d79

In [8]:
import pandas as pd

In [9]:
data = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday']
new_series = pd.Series(data, index=['a','b','c','d','e', 'f'])
new_series.loc[['a','b']]

a    sunday
b    monday
dtype: object

In [10]:
x = pd.DataFrame(data=[
    [1,2,3,4],
    [5,4,5,6]
])
x.sum(axis=0)

0     6
1     6
2     8
3    10
dtype: int64

In [11]:
# soal 1
data = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember']
example_1 = pd.Series(data, index=[i for i in range(1,13)])
example_1

1       Januari
2      Februari
3         Maret
4         April
5           Mei
6          Juni
7          Juli
8       Agustus
9     September
10      Oktober
11     November
12     Desember
dtype: object

In [12]:
example_1.index = ['bulan ke-'+str(i) for i in range(1,13)]
example_1

bulan ke-1       Januari
bulan ke-2      Februari
bulan ke-3         Maret
bulan ke-4         April
bulan ke-5           Mei
bulan ke-6          Juni
bulan ke-7          Juli
bulan ke-8       Agustus
bulan ke-9     September
bulan ke-10      Oktober
bulan ke-11     November
bulan ke-12     Desember
dtype: object

# Bootcamp Pandas - Conditional Selection and Modifying DataFrame

In [13]:
data = [
    ['Michael Phelps', 23, 'United States', 2008, 8],
    ['Michael Phelps', 19, 'Canada', 2004, 6],
    ['Michael Phelps', 27, 'United States', 2012, 4],
    ['Natalie Coughlin', 25, 'Norway', 2008, 1],
    ['Aleksey Nemov', 24, 'China', 2000, 2],
]
swimm_df = pd.DataFrame(data, columns=['Athlete', 'Age','Country', 'Year', 'Gold Medals'])
swimm_df

Athlete  Age        Country  Year  Gold Medals
0    Michael Phelps   23  United States  2008            8
1    Michael Phelps   19         Canada  2004            6
2    Michael Phelps   27  United States  2012            4
3  Natalie Coughlin   25         Norway  2008            1
4     Aleksey Nemov   24          China  2000            2

In [14]:
# sal nomor 1 tampilkan nama atlet yang berasa dari US
swimm_df[
    swimm_df['Country']=="United States" 
]['Athlete']

0    Michael Phelps
2    Michael Phelps
Name: Athlete, dtype: object

In [15]:
# soal nomor 2 tampilkan nama atlet yang bergabung pada tahun 2008
swimm_df[
    swimm_df['Year']==2008
]

Athlete  Age        Country  Year  Gold Medals
0    Michael Phelps   23  United States  2008            8
3  Natalie Coughlin   25         Norway  2008            1

In [16]:
# soal nomor 3 hapus data dengan atlet yang berusia lebih dari 25 tahun dan berasal dari norway
# ambil data yang usia atlet > 25 tahun
filtering_1 = swimm_df[
    swimm_df['Age']>25
]
filtering_2 = filtering_1[
    filtering_1['Country']=="Norway"
]
# ambil index data yang akan dihapus
index = filtering_2.index

# hapus data
new_swimm_df = swimm_df.drop(index)

In [17]:
new_swimm_df

Athlete  Age        Country  Year  Gold Medals
0    Michael Phelps   23  United States  2008            8
1    Michael Phelps   19         Canada  2004            6
2    Michael Phelps   27  United States  2012            4
3  Natalie Coughlin   25         Norway  2008            1
4     Aleksey Nemov   24          China  2000            2

# Bootcamp Pandas - Reading External Data

## Tugas 1

In [19]:
# soal nomor 1 download file csv

# soal nomor 2
tourism = pd.read_csv('dataset/package_tourism.csv')
tourism

Package      City                   Place_Tourism1  \
0         1   Jakarta                Pasar Tanah Abang   
1         2   Jakarta                Pasar Tanah Abang   
2         3   Jakarta            Perpustakaan Nasional   
3         4   Jakarta                     Pulau Tidung   
4         5   Jakarta            Museum Satria Mandala   
..      ...       ...                              ...   
95       96  Surabaya      Ekowisata Mangrove Wonorejo   
96       97  Surabaya                Ciputra Waterpark   
97       98  Surabaya    Museum Kesehatan Dr. Adhyatma   
98       99  Surabaya  Taman Ekspresi Dan Perpustakaan   
99      100  Surabaya              Taman Buah Surabaya   

              Place_Tourism2                  Place_Tourism3  \
0               Taman Ayodya                  Museum Tekstil   
1         Pasar Taman Puring            Pasar Petak Sembilan   
2                      Monas                 Masjid Istiqlal   
3             Pulau Bidadari                      Pulau Pari   
4              Museum Wayang           Museum Bahari Jakarta   
..                       ...                             ...   
95     Taman Harmoni Keputih             Taman Kunang-Kunang   
96             Kenjeran Park         Kebun Binatang Surabaya   
97  Patung Buddha Empat Rupa            Taman Hiburan Rakyat   
98   Museum De Javasche Bank  Surabaya Museum (Gedung Siola)   
99       Hutan Bambu Keputih                Taman Barunawati   

                                       Place_Tourism4  \
0                                                 NaN   
1                                                 NaN   
2                                                 NaN   
3                                       Pulau Pramuka   
4   Museum Macan (Modern and Contemporary Art in N...   
..                                                ...   
95                    Taman Ekspresi Dan Perpustakaan   
96                        Food Junction Grand Pakuwon   
97                                      Taman Bungkul   
98                                Museum Mpu Tantular   
99                               Kebun Bibit Wonorejo   

                      Place_Tourism5  
0                                NaN  
1                                NaN  
2                                NaN  
3                      Pulau Pelangi  
4                                NaN  
..                               ...  
95           Museum De Javasche Bank  
96          | Atlantis Land Surabaya  
97      Taman Flora Bratang Surabaya  
98  Taman Air Mancur Menari Kenjeran  
99                       Taman Mundu  

[100 rows x 7 columns]

In [21]:
# soal nomor 2
tourism.rename(
    columns={
        'Package': 'Paket',
        'City': 'Kota',
        'Place_Tourism1': 'Destinasi 1'
    }
)

Paket      Kota                      Destinasi 1  \
0       1   Jakarta                Pasar Tanah Abang   
1       2   Jakarta                Pasar Tanah Abang   
2       3   Jakarta            Perpustakaan Nasional   
3       4   Jakarta                     Pulau Tidung   
4       5   Jakarta            Museum Satria Mandala   
..    ...       ...                              ...   
95     96  Surabaya      Ekowisata Mangrove Wonorejo   
96     97  Surabaya                Ciputra Waterpark   
97     98  Surabaya    Museum Kesehatan Dr. Adhyatma   
98     99  Surabaya  Taman Ekspresi Dan Perpustakaan   
99    100  Surabaya              Taman Buah Surabaya   

              Place_Tourism2                  Place_Tourism3  \
0               Taman Ayodya                  Museum Tekstil   
1         Pasar Taman Puring            Pasar Petak Sembilan   
2                      Monas                 Masjid Istiqlal   
3             Pulau Bidadari                      Pulau Pari   
4              Museum Wayang           Museum Bahari Jakarta   
..                       ...                             ...   
95     Taman Harmoni Keputih             Taman Kunang-Kunang   
96             Kenjeran Park         Kebun Binatang Surabaya   
97  Patung Buddha Empat Rupa            Taman Hiburan Rakyat   
98   Museum De Javasche Bank  Surabaya Museum (Gedung Siola)   
99       Hutan Bambu Keputih                Taman Barunawati   

                                       Place_Tourism4  \
0                                                 NaN   
1                                                 NaN   
2                                                 NaN   
3                                       Pulau Pramuka   
4   Museum Macan (Modern and Contemporary Art in N...   
..                                                ...   
95                    Taman Ekspresi Dan Perpustakaan   
96                        Food Junction Grand Pakuwon   
97                                      Taman Bungkul   
98                                Museum Mpu Tantular   
99                               Kebun Bibit Wonorejo   

                      Place_Tourism5  
0                                NaN  
1                                NaN  
2                                NaN  
3                      Pulau Pelangi  
4                                NaN  
..                               ...  
95           Museum De Javasche Bank  
96          | Atlantis Land Surabaya  
97      Taman Flora Bratang Surabaya  
98  Taman Air Mancur Menari Kenjeran  
99                       Taman Mundu  

[100 rows x 7 columns]

In [22]:
tourism.shape

(100, 7)

## Tugas 2

# Bootcamp Data Analysis - Statistika Dasar

In [23]:
data_pelanggaran_lalu_lintas = pd.read_csv('dataset/Data-Penindakan-Pelanggaran-Lalu-Lintas.csv')
data_pelanggaran_lalu_lintas

bulan                   wilayah  bap_tilang  stop_operasi  bap_polisi  \
0    Januari             Bidang Dalops          44           139           0   
1    Januari    Sudinhub Jakarta Pusat          47             2          52   
2    Januari    Sudinhub Jakarta Utara         166            27           0   
3    Januari  Sudinhub Jakarta Selatan          44             1           0   
4    Januari    Sudinhub Jakarta Barat         184            70           0   
5    Januari    Sudinhub Jakarta Timur         191           141           0   
6   Februari             Bidang Dalops          37           143           0   
7   Februari    Sudinhub Jakarta Pusat          48             7          42   
8   Februari    Sudinhub Jakarta Utara         251            27          31   
9   Februari  Sudinhub Jakarta Selatan         129            12           0   
10  Februari    Sudinhub Jakarta Barat         229            60           0   
11  Februari    Sudinhub Jakarta Timur         276           146           0   
12     Maret             Bidang Dalops          90           203           0   
13     Maret    Sudinhub Jakarta Pusat          68            10           0   
14     Maret    Sudinhub Jakarta Utara         323            37           0   
15     Maret  Sudinhub Jakarta Selatan         479            51           0   
16     Maret    Sudinhub Jakarta Barat         270           101           0   
17     Maret    Sudinhub Jakarta Timur         253           129           0   
18     April             Bidang Dalops          78           108           0   
19     April    Sudinhub Jakarta Pusat          93            21           0   
20     April    Sudinhub Jakarta Utara         293            22          12   
21     April  Sudinhub Jakarta Selatan         454            42           0   
22     April    Sudinhub Jakarta Barat         233            97           0   
23     April    Sudinhub Jakarta Timur         274           113           0   
24       Mei             Bidang Dalops          47            88           0   
25       Mei    Sudinhub Jakarta Pusat          30            10           0   
26       Mei    Sudinhub Jakarta Utara         174            10          16   
27       Mei  Sudinhub Jakarta Selatan         203            29           2   
28       Mei    Sudinhub Jakarta Barat         156            82           0   
29       Mei    Sudinhub Jakarta Timur         162           107           0   
30      Juni             Bidang Dalops         113           129           0   
31      Juni    Sudinhub Jakarta Pusat          24             9           0   
32      Juni    Sudinhub Jakarta Utara         365            29          39   
33      Juni  Sudinhub Jakarta Selatan         390            22          16   
34      Juni    Sudinhub Jakarta Barat         176            81           0   
35      Juni    Sudinhub Jakarta Timur         217           116           0   
36      Juli             Bidang Dalops          72            80           0   
37      Juli    Sudinhub Jakarta Pusat          12             6           0   
38      Juli    Sudinhub Jakarta Utara         224            20          24   
39      Juli  Sudinhub Jakarta Selatan          95             2           8   
40      Juli    Sudinhub Jakarta Barat          36            32           0   
41      Juli    Sudinhub Jakarta Timur         104            72           0   

    stop_operasi_polisi  penderekan  ocp_roda_dua  ocp_roda_empat  \
0                     0          73             0               0   
1                     0         184           237              15   
2                     0         174             0               0   
3                     0          61            42              75   
4                     0         202            10               5   
5                     0         137             0               0   
6                     0          95             2               1   
7             

In [24]:
data_pelanggaran_lalu_lintas.dtypes

bulan                  object
wilayah                object
bap_tilang              int64
stop_operasi            int64
bap_polisi              int64
stop_operasi_polisi     int64
penderekan              int64
ocp_roda_dua            int64
ocp_roda_empat          int64
angkut_motor            int64
dtype: object

In [25]:
# soal nomor 3 tentukan mean dan median dari setiap masing-masing variabel numerik
print(data_pelanggaran_lalu_lintas['stop_operasi'].mean())
print(data_pelanggaran_lalu_lintas['stop_operasi'].median())

62.69047619047619
46.5


In [27]:
# soal nomor 4 tentukan std serta quartile 1,2,3 pada setiap masing-masing variabel numerik
print(data_pelanggaran_lalu_lintas['stop_operasi'].std())
print(np.quantile(data_pelanggaran_lalu_lintas['stop_operasi'], [.25, .5, .75]))

52.447645484243445
[ 20.25  46.5  105.5 ]


In [38]:
# soal nomor 5 tentukan mean dari variabel bap_tilang pada setiap masing-masing bulan
data_pelanggaran_lalu_lintas.groupby(by=['bulan'])[['bap_tilang', 'stop_operasi']].sum()

bap_tilang  stop_operasi
bulan                             
April           1425           403
Februari         970           395
Januari          676           380
Juli             543           212
Juni            1285           386
Maret           1483           531
Mei              772           326