# Import Libraries

In [1]:
import numpy as np

# Numpy Introduction

## Creating Numpy Array

In [2]:
example_data = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [4,5,3],
            [9,4,3]
        ]
    ]
)

In [3]:
example_data.shape

(2, 2, 3)

In [10]:
x = np.array([1,2,3,4])
x.reshape((2,2))

array([[1, 2],
       [3, 4]])

In [12]:
arr_split_example = np.array(
    [
        np.arange(10),
        np.arange(40,60,2)
    ]
)
# Membagi array menjadi 10 sama besar
arr_splitted = np.hsplit(arr_split_example,10)
print(arr_splitted)

[[ 0]
 [40]]


In [14]:
arr_splitted = np.vsplit(arr_split_example, 2)

In [15]:
arr_splitted

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[40, 42, 44, 46, 48, 50, 52, 54, 56, 58]])]

In [16]:
xx = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

In [18]:
xx[:, 2]

array([ 3,  6,  9, 12])